[package]
name = "deno_bindgen-learn"
version = "0.1.0"
edition = "2021"

[lib]
name = "deno_bindgen_learn"
path = "src/lib_simple.rs"
crate-type = ["cdylib"]

[dependencies]
deno_bindgen = "0.8.1"

# 无依赖 - 纯 Rust FFI 实现
